config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true, uniqueness: { scope: [:cocktail_id] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: params[:id].to_i)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save

    redirect_to new_cocktail_dose_path(@cocktail)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(cocktail: @cocktail)
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @dose.save
    redirect_to cocktail_path(@dose.cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.standard.co.uk/s3fs-public/thumbnails/image/2016/09/30/10/cocktails.jpg?width=1000&height=614&fit=bounds&format=pjpg&auto=webp&quality=70&crop=16:9,offset-y0.5');">
  <div class="banner-content">
    <h1>Cocktails</h1>
    <p>Get recipes of all cocktails in the world</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: url('<%= cocktail.photo %>')">
          <div class="card-description">
            <h4><%= link_to cocktail.name, cocktail_path(cocktail) %></h4>
            <ul>
              <% cocktail.ingredients.each do |ingredient| %>
                <li><%= ingredient.name (@ingredient.dose) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <div class="card-description">
          <p>Add a new cocktail</p>
          <%= simple_form_for(@cocktail) do |f| %>
            <%= f.input :name %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.button :submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<ul>
<% @doses.each do |dose| %>
  <li><%= dose.ingredient.name %>: <%= dose.description %> (<%= link_to "delete", dose_path(dose), method: :delete %>)</li>
  <br>
<% end %>
</ul>
<p><%= link_to "Add ingredients", new_cocktail_dose_path(@cocktail) %></p>
<p><%= link_to "See all cocktails", cocktails_path %></p>

app/views/doses/new.html.erb
<div class="container">
  <h1>New Ingredient</h1>
  <%= simple_form_for [@cocktail, @ingredient, @dose] do |f| %>
    <%= f.association :ingredient, label: 'Choose your ingredient' %>
    <%= f.input :description, label: 'How much would you put?' %>
    <%= f.submit 'Add ingredient' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>